"use client";

import { useState } from "react";
import {
    Dialog,
    DialogContent,
    DialogDescription,
    DialogHeader,
    DialogTitle,
    DialogFooter
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import {
    Select,
    SelectContent,
    SelectItem,
    SelectTrigger,
    SelectValue
} from "@/components/ui/select";
import { toast } from "sonner";

interface Chapter {
    id: string;
    title: string;
    order: number;
    content: string | null;
}

interface ExportModalProps {
    isOpen: boolean;
    onClose: () => void;
    story: {
        id: string;
        title: string;
        synopsis?: string | null;
        genre?: string | null;
        chapters: Chapter[];
    };
    currentChapterId?: string;
    currentChapterTitle?: string;
    editorContent?: string;
}

function cleanHtmlToMarkdown(html: string) {
    if (!html) return "";
    let text = html;
    // Replace paragraph tags with newlines
    text = text.replace(/<p[^>]*>/gi, "").replace(/<\/p>/gi, "\n\n");
    // Headers
    text = text.replace(/<h1[^>]*>/gi, "# ").replace(/<\/h1>/gi, "\n\n");
    text = text.replace(/<h2[^>]*>/gi, "## ").replace(/<\/h2>/gi, "\n\n");
    text = text.replace(/<h3[^>]*>/gi, "### ").replace(/<\/h3>/gi, "\n\n");
    // Emphasis
    text = text.replace(/<strong[^>]*>(.*?)<\/strong>/gi, "**$1**");
    text = text.replace(/<em[^>]*>(.*?)<\/em>/gi, "*$1*");
    text = text.replace(/<u[^>]*>(.*?)<\/u>/gi, "_$1_");
    // Lists
    text = text.replace(/<ul[^>]*>/gi, "").replace(/<\/ul>/gi, "\n");
    text = text.replace(/<li[^>]*>(.*?)<\/li>/gi, "- $1\n");
    text = text.replace(/<ol[^>]*>/gi, "").replace(/<\/ol>/gi, "\n");
    // Remove other HTML tags
    text = text.replace(/<[^>]*>/g, "");
    // Decode common HTML entities
    text = text.replace(/&nbsp;/g, " ")
               .replace(/&amp;/g, "&")
               .replace(/&lt;/g, "<")
               .replace(/&gt;/g, ">")
               .replace(/&quot;/g, '"')
               .replace(/&#39;/g, "'")
               .replace(/&ldquo;/g, '"')
               .replace(/&rdquo;/g, '"');
    return text.trim();
}

export function ExportModal({
    isOpen,
    onClose,
    story,
    currentChapterId,
    currentChapterTitle,
    editorContent
}: ExportModalProps) {
    const [scope, setScope] = useState<"chapter" | "story">(currentChapterId ? "chapter" : "story");
    const [format, setFormat] = useState<"markdown" | "pdf">("markdown");
    const [font, setFont] = useState<"serif" | "sans">("serif");
    const [spacing, setSpacing] = useState<"single" | "double">("double");
    const [includeCover, setIncludeCover] = useState(true);
    const [includePageBreaks, setIncludePageBreaks] = useState(true);

    const handleExport = () => {
        if (format === "markdown") {
            try {
                let markdown = "";
                
                // Add Cover Page
                if (includeCover) {
                    markdown += `# ${story.title.toUpperCase()}\n\n`;
                    if (story.genre) markdown += `Genre: ${story.genre}\n\n`;
                    if (story.synopsis) markdown += `Synopsis: ${story.synopsis}\n\n`;
                    markdown += `Generated by Storack\n\n`;
                    markdown += `=========================================\n\n`;
                }

                if (scope === "chapter" && currentChapterId) {
                    const chapterContent = editorContent || "";
                    markdown += `# Chapter: ${currentChapterTitle || "Untitled"}\n\n`;
                    markdown += cleanHtmlToMarkdown(chapterContent);
                } else {
                    const sortedChapters = [...story.chapters].sort((a, b) => a.order - b.order);
                    sortedChapters.forEach((ch, idx) => {
                        markdown += `# Chapter ${ch.order}: ${ch.title}\n\n`;
                        markdown += cleanHtmlToMarkdown(ch.content || "");
                        markdown += "\n\n";
                        if (includePageBreaks && idx < sortedChapters.length - 1) {
                            markdown += `---\n\n`;
                        }
                    });
                }

                // Download markdown file
                const blob = new Blob([markdown], { type: "text/markdown;charset=utf-8;" });
                const url = URL.createObjectURL(blob);
                const link = document.createElement("a");
                link.href = url;
                const filename = scope === "chapter"
                    ? `${story.title.toLowerCase()}-${(currentChapterTitle || "chapter").toLowerCase().replace(/\s+/g, "-")}.md`
                    : `${story.title.toLowerCase()}-full-manuscript.md`;
                link.setAttribute("download", filename);
                document.body.appendChild(link);
                link.click();
                document.body.removeChild(link);
                
                toast.success("Markdown export completed");
                onClose();
            } catch (error) {
                console.error(error);
                toast.error("Failed to compile Markdown");
            }
        } else {
            // PDF Export via Print Window
            const params = new URLSearchParams();
            if (scope === "chapter" && currentChapterId) {
                params.set("chapterId", currentChapterId);
            }
            params.set("font", font);
            params.set("spacing", spacing);
            params.set("cover", includeCover ? "true" : "false");
            params.set("breaks", includePageBreaks ? "true" : "false");

            const printUrl = `/stories/${story.id}/export?${params.toString()}`;
            window.open(printUrl, "_blank");
            
            toast.success("PDF print preview opened");
            onClose();
        }
    };

    return (
        <Dialog open={isOpen} onOpenChange={onClose}>
            <DialogContent className="sm:max-w-[425px]">
                <DialogHeader>
                    <DialogTitle>Export Manuscript</DialogTitle>
                    <DialogDescription>
                        Compile and format your writing into standard formats.
                    </DialogDescription>
                </DialogHeader>

                <div className="grid gap-4 py-4">
                    {/* Scope Selector */}
                    {currentChapterId && (
                        <div className="grid grid-cols-4 items-center gap-4">
                            <Label htmlFor="scope" className="text-right text-xs">
                                Scope
                            </Label>
                            <Select value={scope} onValueChange={(val: any) => setScope(val)}>
                                <SelectTrigger className="col-span-3 text-xs">
                                    <SelectValue />
                                </SelectTrigger>
                                <SelectContent>
                                    <SelectItem value="chapter" className="text-xs">Current Chapter</SelectItem>
                                    <SelectItem value="story" className="text-xs">Full Manuscript</SelectItem>
                                </SelectContent>
                            </Select>
                        </div>
                    )}

                    {/* Format Selector */}
                    <div className="grid grid-cols-4 items-center gap-4">
                        <Label htmlFor="format" className="text-right text-xs">
                            Format
                        </Label>
                        <Select value={format} onValueChange={(val: any) => setFormat(val)}>
                            <SelectTrigger className="col-span-3 text-xs">
                                <SelectValue />
                            </SelectTrigger>
                            <SelectContent>
                                <SelectItem value="markdown" className="text-xs">Markdown (.md)</SelectItem>
                                <SelectItem value="pdf" className="text-xs">PDF Document (.pdf)</SelectItem>
                            </SelectContent>
                        </Select>
                    </div>

                    {/* PDF Formatting Options */}
                    {format === "pdf" && (
                        <>
                            {/* Font Select */}
                            <div className="grid grid-cols-4 items-center gap-4">
                                <Label htmlFor="font" className="text-right text-xs">
                                    Typography
                                </Label>
                                <Select value={font} onValueChange={(val: any) => setFont(val)}>
                                    <SelectTrigger className="col-span-3 text-xs">
                                        <SelectValue />
                                    </SelectTrigger>
                                    <SelectContent>
                                        <SelectItem value="serif" className="text-xs">Serif (Classic Georgia)</SelectItem>
                                        <SelectItem value="sans" className="text-xs">Sans-Serif (Modern Inter)</SelectItem>
                                    </SelectContent>
                                </Select>
                            </div>

                            {/* Spacing Select */}
                            <div className="grid grid-cols-4 items-center gap-4">
                                <Label htmlFor="spacing" className="text-right text-xs">
                                    Spacing
                                </Label>
                                <Select value={spacing} onValueChange={(val: any) => setSpacing(val)}>
                                    <SelectTrigger className="col-span-3 text-xs">
                                        <SelectValue />
                                    </SelectTrigger>
                                    <SelectContent>
                                        <SelectItem value="double" className="text-xs">Double Spaced (Standard)</SelectItem>
                                        <SelectItem value="single" className="text-xs">Single Spaced (Compact)</SelectItem>
                                    </SelectContent>
                                </Select>
                            </div>
                        </>
                    )}

                    {/* Toggle Settings */}
                    <div className="flex items-center justify-between border-t pt-4">
                        <Label htmlFor="cover" className="text-xs">
                            Include Cover Page
                        </Label>
                        <Switch
                            id="cover"
                            checked={includeCover}
                            onCheckedChange={setIncludeCover}
                        />
                    </div>

                    <div className="flex items-center justify-between">
                        <Label htmlFor="breaks" className="text-xs">
                            Page Breaks per Chapter
                        </Label>
                        <Switch
                            id="breaks"
                            checked={includePageBreaks}
                            onCheckedChange={setIncludePageBreaks}
                        />
                    </div>
                </div>

                <DialogFooter>
                    <Button variant="outline" onClick={onClose} size="sm">Cancel</Button>
                    <Button onClick={handleExport} size="sm">Export</Button>
                </DialogFooter>
            </DialogContent>
        </Dialog>
    );
}
